version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"         # Root where Dockerfile lives
    schedule:
      interval: "daily"   # Needed for Dependabot to run, but won't trigger build unless PR is merged
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
