name: Build and Publish Docker Image

on:
  push:
    paths:
      - dotnet-runtime-Dockerfile
      - .github/workflows/docker-publish.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dotnet-runtime-Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/dotnet-runtime:latest
